version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  AfterInstall:
    - location: scripts/install
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start
      timeout: 100
      runas: root
  ValidateService:
    - location: scripts/test
      timeout: 100
      runas: root